<?php
require_once('custom-post-types/languages.php');
require_once('custom-post-types/videos.php');
require_once('custom-post-types/lexicons.php');
require_once('custom-post-types/resources.php');
require_once('custom-post-types/fellows.php');
require_once('custom-post-types/team.php');
require_once('custom-post-types/partners.php');
require_once('custom-post-types/faq.php');
require_once('custom-post-types/reports.php');
require_once('custom-post-types/events.php');
require_once('custom-post-types/careers.php');
require_once('custom-post-types/documents.php');