<?php
require_once('includes/enqueue-scripts.php');
require_once('includes/class-wt-rest-posts-controller.php');
require_once('includes/custom-post-types.php');
require_once('includes/menus.php');
require_once('includes/search-filter.php');
require_once('includes/template-helpers.php');
require_once('includes/rest-endpoints.php');
require_once('includes/batch-operations.php');
require_once('includes/admin-helpers.php');
